networks:
    webmenu:
        external: false

services:
    webmenu_db:
        image: mongo
        container_name: webmenu_db
        networks:
            - webmenu
        restart: unless-stopped
        volumes:
            - ${DATA_ROOT}/db:/data/db

    webmenu_api:
        build: backend
        image: webmenu_api
        container_name: webmenu_api
        networks:
            - webmenu
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ${DATA_ROOT}/server:/data
        environment:
            - AUTH_TOKEN=${AUTH_TOKEN}
